name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
      - master  # Adding master in case that's your default branch
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.env.example'
  workflow_dispatch:

# Add permissions for GITHUB_TOKEN
permissions:
  contents: read
  packages: write

jobs:
      push-app-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './apps/api'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Debug Trigger Event'
            run: |
              echo "Event name: ${{ github.event_name }}"
              echo "Branch name: ${{ github.ref }}"
              echo "Commit SHA: ${{ github.sha }}"
              echo "Repository: ${{ github.repository }}"
              echo "Workspace: ${{ github.workspace }}"
              ls -la

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build and Push API Image'
            run: |
              docker build . --tag ghcr.io/${{github.repository_owner}}/firecrawl-plus:latest
              docker push ghcr.io/${{github.repository_owner}}/firecrawl-plus:latest