name: Self-hosted Server Test Suite

on:
  pull_request:
    branches:
      - main
    paths:
      - apps/api/**

env:
  PORT: 3002
  REDIS_URL: redis://localhost:6379
  HOST: 0.0.0.0
  ENV: ${{ secrets.ENV }}
  TEST_SUITE_SELF_HOSTED: true

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        openai: [true, false]
        serper: [true, false]
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    env:
      OPENAI_API_KEY: ${{ matrix.openai == true && secrets.OPENAI_API_KEY || '' }}
      SERPER_API_KEY: ${{ matrix.serper == true && secrets.SERPER_API_KEY || '' }}
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: './apps/api/pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
        working-directory: ./apps/api
      - name: Start the application
        run: npm start > api.log 2>&1 &
        working-directory: ./apps/api
        id: start_app
      - name: Start workers
        run: npm run workers > worker.log 2>&1 &
        working-directory: ./apps/api
        id: start_workers
      - name: Wait for server
        run: pnpx wait-on tcp:3002 -t 15s
      - name: Run snippet tests
        run: |
          npm run test:snips
        working-directory: ./apps/api
      - name: Kill instances
        if: always()
        run: pkill -9 node
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Logs (openai ${{ matrix.openai }}, serper ${{ matrix.serper }})
          path: |
            ./apps/api/api.log
            ./apps/api/worker.log
